name: validator
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.0.11
  loading_animation_widget: ^1.3.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  flutter_pdfview: ^1.4.1
  dio: ^5.0.0
  path_provider: ^2.0.0
  flutter_file_downloader: ^2.1.0
  open_file: ^3.5.10
  fl_chart: ^0.68.0 #ver 1.1.0: error the method 'translateByDouble' isn't defined for the class 'Matrix4'.
  date_picker_plus: ^3.0.2
  app_badge_plus: ^1.2.3
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/background_login.jpg
    - assets/images/bg-01.jpg

    - assets/cards/red.png
    - assets/cards/yellow.png
    - assets/cards/blue.png
    - assets/cards/green.png

    - assets/cards/total_pengeluaran.png
    - assets/cards/tunai_gantung.png
